spring.data.mongodb.uri=mongodb://localhost:27017/cloudstorage
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://ideal-aardvark-74.clerk.accounts.dev
clerk.jwks-url=https://ideal-aardvark-74.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_ww0RyOiLMfJels9PPC8M3pjZBSPzIuBX

#file upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB